// <auto-generated />
using System;
using Fiap.Aula03.Web.Exemplo.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fiap.Aula03.Web.Exemplo.Migrations
{
    [DbContext(typeof(FiapGamesContext))]
    [Migration("20211007010048_Relacionamentos")]
    partial class Relacionamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnderecoId");

                    b.ToTable("Tbl_Endereco");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Conquistas")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JogadorId");

                    b.ToTable("Tbl_Jogador");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Jogo", b =>
                {
                    b.Property<int>("JogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Lancamento");

                    b.Property<bool?>("Multiplataforma")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Plataforma")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoraId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JogoId");

                    b.HasIndex("ProdutoraId");

                    b.ToTable("Tbl_Jogo");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.JogoJogador", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.HasKey("JogoId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("Tbl_Jogo_Jogador");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Produtora", b =>
                {
                    b.Property<int>("ProdutoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoraId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Tbl_Produtora");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Jogo", b =>
                {
                    b.HasOne("Fiap.Aula03.Web.Exemplo.Models.Produtora", "Produtora")
                        .WithMany("Jogos")
                        .HasForeignKey("ProdutoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtora");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.JogoJogador", b =>
                {
                    b.HasOne("Fiap.Aula03.Web.Exemplo.Models.Jogador", "Jogador")
                        .WithMany("JogoJogadores")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Aula03.Web.Exemplo.Models.Jogo", "Jogo")
                        .WithMany("JogoJogadores")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Produtora", b =>
                {
                    b.HasOne("Fiap.Aula03.Web.Exemplo.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Jogador", b =>
                {
                    b.Navigation("JogoJogadores");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Jogo", b =>
                {
                    b.Navigation("JogoJogadores");
                });

            modelBuilder.Entity("Fiap.Aula03.Web.Exemplo.Models.Produtora", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
